### ISSUE TITLE
Meetup checklist

### ISSUE THREAD

**Issue by maurolepore** [dsincubator/template#2]
## Before

- [x] Create a repo from the [dsincubator/template](https://github.com/dsincubator/template) and prepare the materials.
- [x] Announce in the most appropriate channel
- [x] Create/update the calendar invitation.

## During

- [x] Start the meeting.
- [ ] Nominate a person to act as co-host, moderator, and time-keeper.
- [ ] Share the screen.
- [ ] Record.
- [ ] Questions, comments, discussion.
- [ ] End

## After

- [ ] Upload the video publicly, e.g., on YouTube.
  - Chapter title as it appears in the repository.
  - Chapter description as it appears in the repository.
- [ ] Add it to the general playlist, where all the videos are.
- [ ] Add it to the series playlist, using the repository name.
- [ ] Announce on media, e.g., on LinkedIn, including:
  - Chapter title as it appears in the repository.
  - Chapter description as it appears in the repository.
  - Link to the repo.
  - Link to the video.
  - Link to the playlist.
  - Link to the project's website, e.g., the homepage of a
- [ ] Update resources in the meetup repo
